### ISSUE TITLE
Swagger UI via GitHub Pages? 

### ISSUE THREAD

**Issue by Holzhaus** [rain0r/listenbrainz-openapi#1]
Have you considered using GitHub Actions to deploy the SwaggerUI to GitHub pages? I think this would make this API spec easier to use if you don't need the code generation feature.

**Comment by rain0r** [comment]
That's a really good idea!

I just set up a Github Action to do that.

Link: https://rain0r.github.io/listenbrainz-openapi/index.html#/

There's an error somewhere buried inside but the most things work.
